#!/bin/bash
echo $PWD
if [[ $PWD == *"delivery_test/drive-t186ref-foundation"* ]]; then
	./utils/scripts/bootburn/bootburn.sh $@
	result="$?"
	success="notifylow"
	error="notifycrit"

	if [ "0" = "$result" ] ; then
		cmd=$succes
	else
		cmd=$error
	fi
	sbc $cmd $HOSTNAME $PWD "\nbootburn" $@
else
	echo "wrong folder"
fi

