#!/bin/bash

function init()
{
	tar=$1
	echo "Target: $tar"
	if [[ "t19x" == "$tar" ]]; then
		export TAR_SOC="t19x"
	elif [[ "t18x" == "$tar" ]]; then
		export TAR_SOC="t186"
	else
		echo "None supported target given!"
		echo "Only \"t19x\" and \"t18x\" are supported."
		exit -1
	fi
	export QUICKBOOT_CPU_CROSS_COMPILE=${CROSS_COMPILE}
	export TEGRA_TOP=$PWD/../../
	export TARGET_SOC=${TAR_SOC}
	export ARCH=arm64
}

function clean()
{
	init $1
	echo "Cleaning $TAR_SOC"
	make -j5 clean
}

function build()
{
	init $1
	echo "Building $TAR_SOC"
	make -j5 native_production_defconfig
	make -j5
}

if [[ $CC != *"aarch64-gnu-linux-gcc"* ]]; then
	echo "Sourcing ntg7 sdk"
	source /data/sdk/ntg/environment-setup-aarch64-gnu-linux
	echo "CC = $CC"
fi

tar=$1
clr="FALSE"
cd bootloader/quickboot/qb-t18x-partner/
if [[ -z "$1" ]]; then
	tar=t19x
fi

if [[ "clean" == "$2" ]]; then
	clr="TRUE"
fi

if [[ "all" == "$tar" ]]; then
	if [[ "TRUE" == "$clr" ]]; then
		clean "t19x"
		clean "t18x"
	else
		build "t19x"
		build "t18x"
	fi
else
	if [[ "TRUE" == "$clr" ]]; then
		clean $tar
	else
		build $tar
	fi
fi

