#!/bin/bash
if [ ! -z $1 ];then
	if [[ $1 == "http"* ]];then
		search="twitch.tv/"
		chan="-channel ${1#*$search}"
	else
		chan="-channel $1"
	fi
fi

/usr/bin/chatty \
-single \
-connect \
-user datgizmo \
-token 8reqjtlni40t0t5vjve2j3z81c81iw \
$chan
 
