#!/bin/bash
if [ ! -z $1 ];then
	chan="-channel $1"
echo $chan
fi

cd ~/git/chatty/build/releases
java -jar Chatty.jar \
-single \
-connect \
-user datgizmo \
-token 8reqjtlni40t0t5vjve2j3z81c81iw \
$chan
 
