#!/bin/bash

path="$HOME/.mutt/mailbox/nordic"

totalcount=$(find $path/*/new -type f | wc -l)
folders=$(find $path/*/new -type d | cut -d '/' -f 7)
msg=""

for f in $folders
do
	c=$(find $path/$f/new -type f | wc -l)
	if [[ "0" < "$c" ]]
	then
		msg="${msg}$c mail(s) in $f\n"
	fi
done

if [[ "0" < "$totalcount" ]]
then
	notify-send "Mail:" "$totalcount new mail(s) in total\n$msg"
	echo "$totalcount"
else
	echo "0"
fi
