#!/bin/bash

taglist="Bitbucket HR IT Jira inbox"
totalcount=$(notmuch count tag:unread)

if [[ "0" < "$totalcount" ]]
then
    for t in $taglist
    do
        c=$(notmuch count tag:unread and tag:$t)
        if [[ "0" < "$c" ]]
        then
            msg="${msg}$c mail(s) in $t\n"
        fi
    done

    notify-send "Mail:" "$totalcount new mail(s) in total\n$msg"
    echo "$totalcount"
else
    echo "0"
fi
