#!/bin/bash

ip="127.0.0.1"
output="/dev/video1"
audio=""
if [ "$2" == "s" ]
then
    pacmd load-module module-alsa-source device=hw:Loopback,1,0
	ip="192.168.0.3"
	output="/dev/video2"
    audio="-a"
fi
if [ "$1" == "0" ]
then
	size="320x240"
elif [ "$1" == "1" ]
then
	size="640x480"
elif [ "$1" == "2" ]
then
	size="960x720"
elif [ "$1" == "3" ]
then
	size="1280x720"
else
	size="1920x1080"
fi

#echo "ffmpeg -i $size -input_format mjpeg -pix_fmt yuyv422 -f v4l2 $output -loglevel 8"
#ffmpeg -i $size -input_format mjpeg -pix_fmt yuyv422 -f v4l2 $output -loglevel 8
echo "/usr/bin/droidcam-cli -v $audio -dev=$output -size=$size $ip 4747"
/usr/bin/droidcam-cli -v $audio -dev=$output -size=$size $ip 4747
