#!/bin/bash

url="http://127.0.0.1:4747/video?"
#url="http://192.168.1.108:4747/video?"
output="/dev/video0"
if [ "$2" == "s" ]
then
	#url="http://192.168.1.108:4747/video?"
	output="/dev/video1"
fi
if [ "$1" == "0" ]
then
	url=$url"320x240"
elif [ "$1" == "1" ]
then
	url=$url"640x480"
elif [ "$1" == "2" ]
then
	url=$url"960x720"
elif [ "$1" == "3" ]
then
	url=$url"1280x720"
else
	url=$url"1920x1080"
fi

echo "ffmpeg -i $url -input_format mjpeg -pix_fmt yuyv422 -f v4l2 $output -loglevel 8"
ffmpeg -i $url -input_format mjpeg -pix_fmt yuyv422 -f v4l2 $output -loglevel 8
