#!/bin/bash

task=$1
#echo $task
#result=(`grep Elapsed */$task -r` ) # | sed 's/.* \([0-9\.]*\) .*/\1/'` )

sum=0
while read -r line; do
	num=`echo $line | sed 's/.* \([0-9.]*\) .*/\1/'`
	file=`echo $line | sed 's/\(^[-.A-Za-z0-9\/_]*\).*/\1/'`
	echo $sum + $num "($file)"
	sum=`echo $sum + $num | bc`
done < <(grep Elapsed */$task -r)

echo $sum
