#!/bin/bash
sink=$(pulsemixer --list-sources | grep -i "default" | awk -F" " '{ b=$3; gsub(",", "", b); print b }')

st=$(pulsemixer --id $sink --get-mute)
if [[ "$st" == "1" ]]
then
	echo "MUTED"
else
	echo "on"
fi
