#!/bin/bash
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
if [ "$1" == "add" ]; then
	/home/swezel/bin/pidgin-remote on
elif [ "$1" == "remove" ]; then
	/home/swezel/bin/pidgin-remote off
fi
