#!/bin/bash
stream=$1
title=""
url=""
#name=""

function getTwitchUsername()
{
	stre=$1
	search="twitch.tv/"
	chan="${stre#*$search}"
	echo $chan
}

function getTwitchTitle()
{
	chan=$(getTwitchUsername $1)
	echo $(curl -s -H "Authorization: Bearer ts0uqmsefzrjrh04gtizfkk48bbtjg" -X GET https://api.twitch.tv/helix/streams\?user_login=$chan | jq -r '[.data[0].user_name,.data[0].title] | @csv' |  awk -F, '/,/ { gsub ("\"",""); print $1": "$2 }')
}

if [[ $stream == *"twitch.tv"* ]]; then
	title=$(getTwitchTitle $stream)
	url=$stream
elif [[ $stream == "http"* ]]; then
	url=$stream
	title="Live stream"
else
	url="twitch.tv/$stream"
	title=$(getTwitchTitle $stream)
fi

if [[ $# -gt 1 ]]; then
	if [[ "$3" == "-q" || "$2" == "-q" ]]; then
		quiet="-Q"
	fi
	if [[ "$2" == "-c" ]]; then
		name=$(getTwitchUsername $1)
		chatty $name >> /dev/null 2>&1 &
	fi
fi

streamlink \
--no-version-check \
--player mpv \
--player-no-close \
--player-args="--title \"$title\" \
{filename} " \
--twitch-oauth-token=ts0uqmsefzrjrh04gtizfkk48bbtjg \
--hls-live-edge 3 \
--hls-segment-threads 1 \
--retry-open 1 \
--retry-streams 1 \
--retry-max 10 \
$quiet \
$url best
