#!/bin/bash
stream=$1
title=""
url=""

if [[ $stream == "http"* ]]; then
	url=$stream
	title="Live stream"
else
	url="twitch.tv/$stream"
	title="Twitchstream $stream"
fi

streamlink \
--no-version-check \
--player-no-close \
--player mpv \
--player-no-close \
--twitch-oauth-token=ts0uqmsefzrjrh04gtizfkk48bbtjg \
--hls-live-edge 1 \
--hds-live-edge 1 \
--hls-segment-threads 1 \
--retry-open 1 \
--retry-streams 1 \
$url best
