#!/bin/bash
stream=$1
title=""
url=""

if [[ $stream == "http"* ]]; then
	url=$stream
	title="Youtube live stream"
else
	url="twitch.tv/$stream"
	title="Twitchstream $stream"
fi

streamlink \
--http-header Client-ID=phiay4sq36lfv9zu7cbqwz2ndnesfd8 \
--no-version-check \
--player-no-close \
--player mpv \
--player-no-close \
--player-args="--hwdec=vdpau \
--hwdec-codecs=all \
--hwdec-image-format=yuv420p \
--vo=vdpau \
--deinterlace=no \
--keep-open=no \
--title \"$title\" \
--force-window \
--force-seekable=yes \
--hr-seek=yes \
--cache-secs=1 \
--cache=4056 \
--hr-seek-framedrop=yes {filename}" \
--twitch-oauth-token 8reqjtlni40t0t5vjve2j3z81c81iw \
--hls-live-edge 1 \
--hds-live-edge 1 \
--hls-segment-threads 1 \
--retry-open 1 \
--retry-streams 1 \
$url best
