#!/usr/bin/python

import sys
import getopt
import psutil
import dbus
import pympris
from see import see
from subprocess import call
from subprocess import check_output
from gi.repository import GObject
from dbus.mainloop.glib import DBusGMainLoop

def getMetaData():
    return (mp.player.Metadata['xesam:artist'][0] + ' - '  + mp.player.Metadata['xesam:album'] + ' - ' + str(mp.player.Metadata['xesam:trackNumber']) + '.' + mp.player.Metadata['xesam:title'])

def writeToFile(string):
    fp = open("/home/swe/tmp/watch", "w")
    unic = string.encode("UTF-8", "strict")
    fp.write(unic)
    fp.close()

def handle_properties_changes(changed_props, invalidated_props):
    status = ""
    title = ""
#    print(changed_props.items())
    for name, value in changed_props.items():
        if "PlaybackStatus" in name:
            status = value
        elif "Metadata" in name:
            if(len(value) > 0):
                title = getMetaData()
    if not status:
        status = mp.player.PlaybackStatus

    if not "play" in status.lower():
        writeToFile("Pause/Stopped")
    elif title:
        writeToFile(title)
    else:
        writeToFile(getMetaData())

def main(argv):
    global bus, mp
    mp = ""
    dbus_loop = DBusGMainLoop()
    bus = dbus.SessionBus(mainloop=dbus_loop)
    players_ids = list(pympris.available_players())
    for player in players_ids:
        mplayer = pympris.MediaPlayer(player, bus)
        if "spoti" in mplayer.root.Identity.lower():
            mp = mplayer
            break
    
    if not mp:
        print "Spotify not found, exiting"
        return -1

    mp.player.register_properties_handler(handle_properties_changes)

    loop = GObject.MainLoop()
    loop.run()
    return

if __name__ == "__main__":
    main(sys.argv[1:])
