#!/bin/bash
cd firmwares/bin/t186
if [ ! -h qb_cpu.bin ]; then
	mv qb_cpu.bin qb_cpu.bin.org
else
	echo "qb.bin is already a symlink"
fi
if [ ! -e qb_cpu.bin.rsu ]; then
	cp /data/stash/ccsrtf/drive5_qb/bootloader/quickboot/qb-t18x-partner/_out/t186/images/qb_cpu.bin qb_cpu.bin.rsu
else
	echo "File already copied"
fi
ln -sf qb_cpu.bin.rsu qb_cpu.bin
ls -al --color=always
