#!/bin/bash
process=$(ps -x | grep sbc_master)
portReg="-p[[:space:]]*([[:digit:]]*)"
nameReg="[[:space:]]([[:alpha:]]*)@"
plugin=""

IFS=$'\n'
for f in $process
do
    if [[ $f =~ $portReg ]]
    then
        port=${BASH_REMATCH[1]}
        export SBC_PORT="$port"
        export SBC_REMOTE_HOST="sewe-sdesk"
        export SBC_REMOTE_PORT="22"
        export SBC_REMOTE_USER="sewe-sdesk"
        if [[ $f =~ $nameReg ]]
        then
            export SBC_USER="${BASH_REMATCH[1]}"
        else
            export SBC_USER="sewe"
        fi
    fi
done
