#!/bin/bash
. ~/bin/sbc-source
critOrLow=false
plugin=""
while getopts "cl" OPT
do
    case $OPT in
        c)
            plugin="crit"
            [[ $critOrLow == true ]] && echo "Only use on of crit or low" && exit 1
            critOrLow=true
        ;;
        l)
            plugin="low"
            [[ $critOrLow == true ]] && echo "Only use on of crit or low" && exit 1
            critOrLow=true
        ;;
    esac
            
done
shift $(( OPTIND-1 ))

sbc notify$plugin $@
