#!/bin/bash

taglist="Bitbucket HR IT Jira Jenkins inbox GH_Helpdesk"
totalcount=$(notmuch count tag:unread)

if [[ "0" < "$totalcount" ]]
then
    for t in $taglist
    do
        c=$(notmuch count tag:unread and tag:$t)
        if [[ "0" < "$c" ]]
        then
            msg="${msg}$c mail(s) in $t\n"
            cc="${cc}$c($t)"
        fi
    done

    sbc-notify "Mail:" "$totalcount new mail(s) in total\n$msg"
else
    echo "0"
fi
