#!/bin/bash
PORT="$2"
NAME="$3"
ACTION="$1"
EXECPATH="$0"

help_me()
{
	printf "%s ACTION PORT NAME\n \
		\n \
		ACTION	--> start or stop \n \
		PORT	--> the port of the server, should be the same as in the PRSERVER_HOST var of local.conf\n \
		NAME	--> name of the sqlite and server file\n \
		The log and sqlite3 file will be created at the folder where the script is executed."\
		"$0"

	exit 1
}

die ()
{
	local message="$1"

	echo "die: $message"
	exit 1 
}

[ "${ACTION}" != "start" ] && [ "${ACTION}" != "stop" ] && help_me
[ -z "${PORT}" ] && die "you need a port parameter"
[ -z "${NAME}" ] && die "you need a name parameter"

path="${EXECPATH%/*}"

bitbake-prserv -f $path/${NAME}.sqlite3 -l $path/${NAME}.log --host=localhost --port ${PORT} --${ACTION} 

