#!/bin/bash

if [ ! -d ~/tmuxtmp ]; then
	mkdir ~/tmuxtmp
fi

fn=""
sn=""
m=""
a=""
cmd=""

if [ $USER == 'gizmo' ]; then
	fn="$HOME/bin/mynetstat enp3s0"
	m="$HOME/bin/playerctrl --player mpd --tmux"
elif [ $HOSTNAME == 'HIKAP426' ]; then
	fn="$HOME/bin/mynetstat em1"
elif [ $USER == 'swe' ]; then
	fn="$HOME/bin/mynetstat enp1s0"
elif [ $USER == 'archgizmo' ]; then
	fn="$HOME/bin/mynetstat eno1"
	m="$HOME/bin/playerctrl --player mpd --tmux"
fi

while true; do
	if [ ! -z "$fn" ]; then
		res=$($fn)
		cmd="#[fg=cyan]$res"
	fi
	if [ ! -z "$sn" ]; then
		res=$($sn)
		cmd="$cmd #[fg=cyan]$res"
	fi
	if [ ! -z "$m" ]; then
		res=$($m)
		cmd="$cmd #[fg=cyan]$res"
	fi

	echo "$cmd" > $HOME/tmuxtmp/tmuxRightStatus
	sleep 1
done
