#!/bin/bash

if [ ! -d ~/tmuxtmp ]; then
	mkdir ~/tmuxtmp
fi

l=""
t=""
cmd=""

l="$HOME/bin/tmux-mem-cpu-load --color -g 5"
t="$HOME/bin/myTop"

while true; do
	cmd=""
	if [ ! -z "$l" ]; then
		res=$($l)
		cmd="$cmd #[fg=cyan,bg=black,dim]$res"
	fi
	if [ ! -z "$t" ]; then
		res=$($t)
		cmd="$cmd #[fg=red]$res"
	fi

	echo "$cmd" > $HOME/tmuxtmp/tmuxLeftStatus
	sleep 1
done
