#!/bin/bash
stream=$1

streamlink \
--http-header Client-ID=phiay4sq36lfv9zu7cbqwz2ndnesfd8 \
--no-version-check \
--player-no-close \
--player mpv \
--player-args="--hwdec=vdpau \
--deinterlace yes \
--keep-open=no \
--title \"Twitch Stream $stream\" \
--force-window \
--force-seekable=yes \
--hr-seek=yes \
--hr-seek-framedrop=yes {filename}" \
--twitch-oauth-token 8reqjtlni40t0t5vjve2j3z81c81iw \
--hls-live-edge 3 \
--hls-segment-threads 1 \
--retry-open 1 \
--retry-streams 1 \
twitch.tv/$stream best
