#!/bin/bash
url=$1
search=":"
ytdlp=""
if [[ $url == *"twitch"* ]]; then
	ytdlp=""
else
	ytdlp="--ytdl"
fi

mpv \
--hwdec=vdpau \
--hwdec-codecs=all \
--hwdec-image-format=yuv420p \
--vo=vdpau \
--deinterlace=no \
--keep-open=no \
--force-window \
--force-seekable=yes \
--hr-seek=yes \
--cache-secs=10 \
--cache=4056 \
$ytdlp \
$url
