#!/bin/bash

URL="https://www.wunderground.com/cgi-bin/findweather/getForecast?query=pws:IMNCHEN1820" 
if [ "$1" == "-g" ]; then
	URL="https://www.wunderground.com/cgi-bin/findweather/getForecast?query=pws:IGILCHIN34"
fi

wget -q -O- $URL | awk -F: '/\"temperature\":|\"humidity\":|\"heatindex\":/ { printf "%s", $2 }' | awk -F, '/,/ { gsub (" ",""); print $1"/"$3"°C "$2"%"}'

