#!/bin/bash

URL="http://api.wunderground.com/api/6d09d0c4b5449254/conditions/q/pws:IKARLSBA24.json"
if [ "$1" == "-g" ]; then
        URL="http://api.wunderground.com/api/6d09d0c4b5449254/conditions/q/pws:IWALDBRO14.json"
fi

wget -q -O- $URL | awk -F: '/\"temp_c\":|humidity\":|\"feelslike_c\":|\"weather\":/ { printf "%s", $2 }' | awk -F, '/,/ { gsub ("\"",""); print $2"/"$4"°C "$3" "$1""}'

