#!/bin/bash
stream=$1
search=":"
url=""
if [[ $stream == *"http"* ]]; then
	url=${stream#*$search}
else
	url=$stream
fi
echo $url

mpv \
--hwdec=vdpau \
--hwdec-codecs=all \
--hwdec-image-format=yuv420p \
--vo=vdpau \
--deinterlace=no \
--keep-open=no \
--force-window \
--force-seekable=yes \
--hr-seek=yes \
--cache-secs=10 \
--cache=4056 \
--ytdl \
ytdl:$url 
